### ISSUE TITLE
무중단 배포 스크립트 작성 - 블루,그린

### ISSUE THREAD

**Issue by yoonseo-han** [boostcampwm-2024/web18-inear#22]
```
.github/
└── workflows/
    ├── deploy.yml     # GitHub Actions 워크플로우 파일
    └── scripts/
        └── deploy.sh  # 실제 배포 스크립트
```

블루/그린 무중단 배포는 다운타임 없이 새 버전을 배포하는 전략

## `deploy.sh` 쉘스크립트 순서

1. 현재 상태 확인:
- Blue 환경(현재 버전)이 포트 3001에서 실행 중
- 모든 트래픽이 Blue로 라우팅됨

2. 새 버전 배포 환경 확인:
- Green 환경(새 버전)을 포트 3002에 배포
- Blue는 여전히 모든 트래픽 처리 중

3. 새로운 환경 구성 및 실행
- Green 환경이 정상 작동하는지 확인
- Nginx 설정을 변경해서 트래픽을 Green으로 전환

4. 완료
- Green이 정상 작동하면 Blue 환경 제거
- 문제 발생 시 즉시 Blue로 롤백 가능

## 로컬 환경에서 Port에 관한 정리

- 클라이언트는 정적파일만 서빙해주기에 별도로 필요하지 않음
- 서버측에서는 별도의 포트 매핑이 진행이 되어야함
- 서버-블루: 
```
services:
  server-blue:
    ports:
      - "3001:3000"  # 호스트의 3001 포트가 컨테이너의 3000 포트로 매핑
```
- 서버-그린:
```
services:
  server-blue:
    ports:
      - "3002:3000"  # 호스트의 3002 포트가 컨테이너의 3000 포트로 매핑
```

## 클라우드 위에서 동작하는 instance들의 주소

- 블루 서버: `server-blue:3000`
- 그린 서버: `server-green:3000`
